-- CREATE TABLE restaurant (
--     id SERIAL NOT NULL PRIMARY KEY,
--     name varchar,
--     distance decimal(4,2) and ("miles"),
--     stars integer CHECK(stars < 6 AND stars > 0),
--     category varchar,
--     favorite_dish varchar,
--     takeout char(1),
--     last_visted_date date
-- );
-- UPDATE restaurant SET distance = CAST()
-- INSERT INTO restaurant VALUES (
--     DEFAULT, 'Moon Tower Inn', 0.2, 4, 'Game-meat & specialty hot dogs', 'Chong', 'Y', '12-18-2018'
-- );
-- INSERT INTO restaurant VALUES (
--     DEFAULT, 'Hoodadak', 29.1, 5, 'Korean fried chicken & savory sides', 'Fried Chicken Wings Large(20)', 'Y', '1-12-2019'
-- );
-- INSERT INTO restaurant VALUES (
--     DEFAULT, 'Hokkaido Japanese Kitchen', 14.5, 4, 'Sushi and Japanese dishes', 'Chopped Scallop', 'Y', '8-24-2018'
-- );

